seed: 1106
CUDA: '7,5'
synced: False
resume: False
ckptPath: ''
doTrain: True
modelNameOrPath: '/data/gj/vicuna-7b-v1.3'
tokenizerNameOrPath: '/data/gj/vicuna-7b-v1.3'
mlpPath: '/data/gj/PromptCompression-vicuna/savedModels/Step16/model_loss_2.0918.pth'
trainFile: '/data/gj/data/samsum/train.json'
valFile: '/data/gj/data/samsum/val.json'
testFile: '/data/gj/data/samsum/test.json'
logSavedPath: '/data/gj/PromptCompression-vicuna/logs'
modelSavedPath: '/data/gj/PromptCompression-vicuna/savedModels'

hParams:
  epochs: 10
  lr: 1e-4
  maxSourceLength: 256
  maxTargetLength: 64
  maxCprsedLength: 64
  cprsedTokens: 32
  evalParams:
    evalStep: 2000